# Generated by Django 5.1.4 on 2025-07-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_datos_pago_pedido_metodo_pago_pedido_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('retiro', 'Retiro en tienda'), ('despacho', 'Despacho a domicilio')], default='retiro', max_length=20),
        ),
    ]
