# Generated by Django 5.1.4 on 2025-07-07 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_tipo_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='direccion_entrega',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='sucursal_retiro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
